# Generated by Django 4.1.7 on 2023-03-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ELibraryBook',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=90)),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.categories')),
            ],
            bases=('about.basemodel',),
        ),
    ]
