# Generated by Django 4.1.7 on 2023-03-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_forvolunteers_gratuitoushelptext_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrarybook',
            name='book_file',
            field=models.FileField(default=1, upload_to='static/assets/book_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elibrarybook',
            name='num_of_pages',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AddField(
            model_name='elibrarybook',
            name='year_of_publication',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2023)]),
        ),
    ]
