# Generated by Django 4.1.7 on 2023-03-06 07:39

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBase',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('fullname', models.CharField(max_length=80, verbose_name='Person Name')),
                ('job_title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('responsibilities', ckeditor.fields.RichTextField()),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('personbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.personbase')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('location', models.CharField(max_length=200)),
            ],
            bases=('accounts.personbase',),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('personbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.personbase')),
                ('biography', ckeditor.fields.RichTextField()),
                ('working_hours_start', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00:00'), django.core.validators.MaxValueValidator('17:00:00')])),
                ('working_hours_end', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00:00'), django.core.validators.MaxValueValidator('17:00:00')])),
            ],
            bases=('accounts.personbase',),
        ),
    ]
