# Generated by Django 4.1.7 on 2023-03-06 07:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseNewsEvents',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('title', models.CharField(max_length=120)),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hashtags', models.ManyToManyField(to='about.hashtag')),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='MigrationLaw',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('migration_law_file', models.FileField(upload_to='')),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('basenewsevents_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basenewsevents')),
                ('image', models.ImageField(blank=True, upload_to='images/events_images/')),
                ('address', models.CharField(max_length=200)),
            ],
            bases=('about.basenewsevents',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('basenewsevents_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basenewsevents')),
                ('image', models.ImageField(blank=True, upload_to='images/news_images/')),
            ],
            bases=('about.basenewsevents',),
        ),
    ]
