# Generated by Django 4.1.7 on 2023-03-06 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_instagrampost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='post_url',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
