# Generated by Django 4.1.7 on 2023-03-07 06:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_instagrampost_post_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/useful_links_images')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YouNeedToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/useful_links_images')),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
