# Generated by Django 4.1.7 on 2023-03-06 07:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('question_title', models.CharField(max_length=150)),
                ('answer', models.TextField()),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('fullname', models.CharField(max_length=90)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('question', models.TextField()),
            ],
            bases=('about.basemodel',),
        ),
    ]
