# Generated by Django 4.1.7 on 2023-03-06 07:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('job_title', models.CharField(max_length=90)),
                ('description', ckeditor.fields.RichTextField()),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('job_type', models.CharField(choices=[('fullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=25)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('resume_file', models.FileField(upload_to='')),
            ],
            bases=('about.basemodel',),
        ),
        migrations.CreateModel(
            name='InternShip',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacancies.volunteer')),
                ('date_of_birth', models.DateField(verbose_name='Tugilgan sana: dd/mm/yyyy')),
                ('region', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Xorazm', 'Xorazm'), ('Navoiy', 'Navoiy'), ("Farg'ona", "Farg'ona"), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Andijon', 'Andijon')], max_length=40)),
                ('job_field', models.CharField(max_length=70)),
                ('desired_start_date', models.DateField(verbose_name='Desired Internship start date')),
                ('job_type_intern', models.CharField(choices=[('fullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=30)),
                ('job_type_after_internship', models.CharField(choices=[('fullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=30)),
                ('university', models.CharField(choices=[('WIUT', 'Westminister'), ('IUT', 'Inha'), ('TDYU', 'Toshkent Davlat Yuridik Universiteti')], max_length=80, null=True)),
                ('faculty', models.CharField(choices=[('CS', 'Computer Science'), ('BS', 'Business')], max_length=80)),
                ('start_date_of_study', models.DateField()),
                ('end_date_of_study', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.CharField(max_length=120)),
            ],
            bases=('vacancies.volunteer',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.basemodel')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('resume_file', models.FileField(upload_to='')),
                ('vacancy_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_obj', to='vacancies.vacancy')),
            ],
            bases=('about.basemodel',),
        ),
    ]
